repos:
  - repo: local
    hooks:
      - id: validation-pipeline
        name: validation-pipeline
        entry: uv run tools/validate.py
        language: system
        pass_filenames: false
        always_run: true
