name: Formatting Check

on:
  push:
    branches:
      - main
    paths:
      - "**.yaml"
      - "**.yml"
      - "**.json"
      - "**.md"
  pull_request:
    branches:
      - main
    paths:
      - "**.yaml"
      - "**.yml"
      - "**.json"
      - "**.md"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run Prettier
        run: npx prettier --check .
